# Generated by Django 3.0.3 on 2020-06-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dgsys2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name': 'Equipment Category', 'verbose_name_plural': 'Equipment Categories'},
        ),
    ]
