# Generated by Django 3.0.3 on 2020-08-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgsys2', '0003_auto_20200724_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
