# Generated by Django 3.0.3 on 2020-11-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgsys2', '0005_auto_20201006_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True, verbose_name='Address Line'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='zip_code',
            field=models.IntegerField(null=True, verbose_name='Zip Code'),
        ),
    ]
